---
title: "STATS_5:Genres"
output: html_document
---

```{r import_data}
library(readr)
features <- read_csv("features_distinct.csv")
View(features)
```

```{r remove_duplicates}
library(dplyr)
features1 <- features %>% distinct_at(vars(-ID, -Popularity), .keep_all = TRUE)  # for the match consider all features + year + genre
print("DONE")
```

```{r drop_rows_with_NaN}
features2 <- na.omit(features1)
View(features2)
print("DONE")
```

```{r inspect}
features2$structure_chorus_repetitions
colnames(features2)
```

## -----------------------------------------------------------------------------------------------------------------------------------------------------------

## ANALYSIS FOR 5 GENRES

------------------------------------------------------------------------

```{r subset+downsample(acrossGenre):5}
#############################
#      SELECT SUB-SET       #
#############################
library(ggplot2)
library(dplyr)
library(rstatix)
# select decades
year_selection <- seq(1991, 2020, by=1)
sub_set_all <- features2[which(features2$Date %in% year_selection),]
hist(sub_set_all$Date)
hist(sub_set_all$Popularity)

# eval genres #
unique(sub_set_all[c("Genre")]) # rap, pop, rock, r-b, country
all_genres <- sub_set_all$Genre
ggplot(data.frame(all_genres), aes(x=all_genres)) + geom_bar()

# select genres #
genres <- c("rap", "pop", "rock", "r-b", "country")
sub_set_all_5genres <- sub_set_all[which(sub_set_all$Genre %in% genres),]

# downsampling #
library(caret)
library(groupdata2)
down_sub_set_all5 <- sub_set_all_5genres
down_sub_set_all5$Date2 <- paste(down_sub_set_all5$Date, down_sub_set_all5$Genre, sep="") # add ID column
set.seed(27)
down_sub_set_all5 <- downsample(down_sub_set_all5, cat_col = "Date2")
hist(down_sub_set_all5$Date)
hist(down_sub_set_all5$Popularity)
all_genres <- down_sub_set_all5$Genre
ggplot(data.frame(all_genres), aes(x=all_genres)) + geom_bar()
```

```{r count}
samples_genre <- which(all_genres == "rap")
length(samples_genre)
```

```{r get_subSet}
write.csv(down_sub_set_all5, "5Genres_SubSet.csv", row.names = TRUE)
```

```{r multiple_regression_date_(initial_model)}
library(lm.beta)
library(olsrr)
library(car)
library(ggplot2)
library(usdm)
library(dplyr)

#############################
#      FIT LINEAR MODEL     #
#############################
# Fit model through lm(outcome ~ predictor)
sub_set5 <- subset(down_sub_set_all5, select=-c(ID, Date2)) # drop not used variables
sub_set5[,which(!names(sub_set5) %in% c("Date", "Genre"))] <- scale(sub_set5[,which(!names(sub_set5) %in% c("Date", "Genre"))]) # Z-score normalisation for the IV
sub_set5A <- sub_set5

for (var in colnames(sub_set5)){
  if (sum(is.na(sub_set5[var])) > 0){
    print(var)
    drops <- c(var)
    sub_set5A <- sub_set5A[ , !(names(sub_set5A) %in% drops)]
  }
}

# drop features with "LIWC" (they are creating lot of noise...)
sub_set5B <- sub_set5A[, -grep("LIWC", colnames(sub_set5A))]


lm.model5 <- lm(Date ~. -Genre, data=sub_set5B)
summary(lm.model5)
```

```{r fix_Collinearity}
#############################
#        COLLINEARITY       # 
#############################
# We check this as first step for multiple regression (skip for linear regression)
# When the variance inflation factor (VIF) is above 10, then there exists multicollinearity (https://www.rdocumentation.org/packages/usdm/versions/1.1-18/topics/vif)
sub_set5B <- subset(sub_set5B, select=-c(lexical_punctuation_count, lexical_hapax_legomenon_ratio, structure_number_of_verses, Genre)) # Remove variables that return NA + categorical

vif.1 <- usdm::vif(as.data.frame(sub_set5B))
vif.1

for (y in seq(1:length(vif.1[,1]))){
  max.to.drop <- vif.1[which.max(vif.1[,2]),]
  if (max.to.drop[,2] > 5){
    sub_set5B <- dplyr::select(sub_set5B, -max.to.drop[,1])
    vif.1 <- usdm::vif(sub_set5B)
    print("Iterating ...")
  }
}

vif.2 <- usdm::vif(sub_set5B)
vif.2
new_sub_set5 <- sub_set5B
```

```{r remove_outliers}
# multicollinear outliyers
new_sub_set5$row_index <- 1:nrow(new_sub_set5)
NO_outliers <- new_sub_set5 %>% group_by(Date) %>% mahalanobis_distance() %>% filter(is.outlier == FALSE) %>% as.data.frame()
sub_set_all5 <- new_sub_set5[which(new_sub_set5$row_index %in% NO_outliers$row_index),]
print("DONE")
```

```{r fix_Kooc's_distance}
##  DROP FEATURES WITH COOK'S DISTANCE > 0.5  ##
new_sub_set5B <- sub_set_all5
for (feature in colnames(sub_set_all5)) {
  #if (feature != "Date"){
  if (feature != "Date" & feature != "Popularity"){
    each.model <- lm(Date ~ eval(parse(text = feature)), data=sub_set_all5)
    cooksd <- cooks.distance(each.model)
    if (max(cooksd) > 0.5){
      print(feature)
      new_sub_set5B <- subset(new_sub_set5B, select=-c(eval(parse(text = feature))))
    }
  }
}
print("DONE")
```

```{r get_final_data}
library(nlme)
library(ggplot2)
# Get filtered data.frame with genre information
sub_set5$row_index <- 1:nrow(sub_set5)
genr_col <- sub_set5[which(sub_set5$row_index %in% sub_set_all5$row_index),]
sel_Data5 <- cbind(sub_set_all5, Genre=genr_col$Genre)
# run initial model
lm.model5.0 <- lm(Date ~ . -Genre -row_index, data=sel_Data5)
plot(lm.model5.0)
```

In order to investigate whether there is a a relationship between Popularity and Genre, as well as the interaction between Popularity:Date and Genre, we start by performing multiple logistic regression considering genre as Dependent Variable and Popularity and Popularity:Date as predictors.

```{r multiple_logistic_regression}
library(mlogit)
library(car)
library(effects)
library(multcomp)
Final_Data5 <- subset(sel_Data5, select=-c(row_index)) 
is.factor(Final_Data5$Genre)

Final_Data5B <- mlogit.data(Final_Data5, choice ="Genre", shape = "wide")
mlogit.model5 <- mlogit(Genre ~ 1 | Date*Popularity, data=Final_Data5B, reflevel = "rap")
summary(mlogit.model5)
exp(mlogit.model5$coefficients)
exp(confint(mlogit.model5))
```

To investigate the relevant features to to predict changes in lyrics over time, multiple linear regression (for each genre individually) is carried out considering year as dependent variable. Since popularity showed to vary across genres, both the lyrics features individually as well as their interaction with popularity will be investigated. Each model was optimised following backwards selection.

```{r descriptive}
library(psych)
describeBy(Final_Data5, Final_Data5$Genre)
```

```{r linear_models_standard}
# select genre
sub_set_rap5 <- Final_Data5[which(Final_Data5$Genre == 'rap'),]
subset_rap5 <- subset(sub_set_rap5, select=-c(Genre))
sub_set_rock5 <- Final_Data5[which(Final_Data5$Genre == 'rock'),]
subset_rock5 <- subset(sub_set_rock5, select=-c(Genre))
sub_set_pop5 <- Final_Data5[which(Final_Data5$Genre == 'pop'),]
subset_pop5 <- subset(sub_set_pop5, select=-c(Genre))
sub_set_rb5 <- Final_Data5[which(Final_Data5$Genre == 'r-b'),]
subset_rb5 <- subset(sub_set_rb5, select=-c(Genre))
sub_set_country5 <- Final_Data5[which(Final_Data5$Genre == 'country'),]
subset_country5 <- subset(sub_set_country5, select=-c(Genre))

lm.rap5 <- lm(Date ~ ., data=subset_rap5)
lm.rock5 <- lm(Date ~ ., data=subset_rock5)
lm.pop5 <- lm(Date ~ ., data=subset_pop5)
lm.rb5 <- lm(Date ~ ., data=subset_rb5)
lm.country5 <- lm(Date ~ ., data=subset_country5)
print("DONE")
```

```{r linear_models_withinGenre}
library(stringr)
sel.model.rap5 <- step(lm.rap5, direction = "backward", test = "F")
toselect.x.rap5 <- summary(sel.model.rap5)$coeff[-1,4] < 1 # Get all predictors (we do not filter by significant level)
relevant.x.rap5 <- names(toselect.x.rap5)[toselect.x.rap5 == TRUE]
interaction.formula.rap5 <- as.formula(paste("Date ~", paste(relevant.x.rap5, collapse= "+Popularity*")))
interaction.model.rap5 <- lm(formula=interaction.formula.rap5, data=subset_rap5)

sel.model.rock5 <- step(lm.rock5, direction = "backward", test = "F")
toselect.x.rock5 <- summary(sel.model.rock5)$coeff[-1,4] < 1 
relevant.x.rock5 <- names(toselect.x.rock5)[toselect.x.rock5 == TRUE] 
interaction.formula.rock5 <- as.formula(paste("Date ~", paste(relevant.x.rock5, collapse= "+Popularity*")))
interaction.model.rock5 <- lm(formula=interaction.formula.rock5, data=subset_rock5)

sel.model.pop5 <- step(lm.pop5, direction = "backward", test = "F")
toselect.x.pop5 <- summary(sel.model.pop5)$coeff[-1,4] < 1
relevant.x.pop5 <- names(toselect.x.pop5)[toselect.x.pop5 == TRUE] 
interaction.formula.pop5 <- as.formula(paste("Date ~", paste(relevant.x.pop5, collapse= "+Popularity*")))
interaction.model.pop5 <- lm(formula=interaction.formula.pop5, data=subset_pop5)

sel.model.rb5 <- step(lm.rb5, direction = "backward", test = "F")
toselect.x.rb5 <- summary(sel.model.rb5)$coeff[-1,4] < 1
relevant.x.rb5 <- names(toselect.x.rb5)[toselect.x.rb5 == TRUE] 
interaction.formula.rb5 <- as.formula(paste("Date ~", paste(relevant.x.rb5, collapse= "+Popularity*")))
interaction.model.rb5 <- lm(formula=interaction.formula.rb5, data=subset_rb5)

sel.model.country5 <- step(lm.country5, direction = "backward", test = "F")
toselect.x.country5 <- summary(sel.model.country5)$coeff[-1,4] < 1
relevant.x.country5 <- names(toselect.x.country5)[toselect.x.country5 == TRUE] 
interaction.formula.country5 <- as.formula(paste("Date ~", paste(relevant.x.country5, collapse= "+Popularity*")))
interaction.model.country5 <- lm(formula=interaction.formula.country5, data=subset_country5)

print("DONE")
```

We do consider the interaction with popularity only for rb since for the otehr genres the interaction does not improve the model significantly.

```{r final_models}
# 3-factor anova (compariosn between: baseline, selected, and interaction models)
anova(sel.model.rap5, interaction.model.rap5)
anova(sel.model.rock5, interaction.model.rock5)
anova(sel.model.pop5, interaction.model.pop5)
anova(sel.model.rb5, interaction.model.rb5)
anova(sel.model.country5, interaction.model.country5)

# We select the best model for each genre
plot(sel.model.rap5)
plot(sel.model.rock5)
plot(sel.model.pop5)
plot(interaction.model.rb5)
plot(sel.model.country5)

summary(sel.model.rap5)
summary(sel.model.pop5)
summary(sel.model.rock5)
summary(interaction.model.rb5)
summary(sel.model.country5)
```

```{r check_relationships}
library(ggplot2)
# have  look to ALL realtionships between DV & IV without transformation
# RAP
for (feature in relevant.x.rap5) {
  print(ggplot(sub_set_rap5, aes(y=eval(parse(text=feature)), x=Date)) +
  geom_smooth(method = "lm", aes(group = 1)) + geom_jitter(alpha = .5) + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) + ggtitle(feature))
}

#ROCK
for (feature in relevant.x.rock5) {
  print(ggplot(sub_set_rock5, aes(y=eval(parse(text=feature)), x=Date)) +
  geom_smooth(method = "lm", aes(group = 1)) + geom_jitter(alpha = .5) + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) + ggtitle(feature))
}

#POP
for (feature in relevant.x.pop5) {
  print(ggplot(sub_set_pop5, aes(y=eval(parse(text=feature)), x=Date)) +
  geom_smooth(method = "lm", aes(group = 1)) + geom_jitter(alpha = .5) + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) + ggtitle(feature))
}

#RB
for (feature in relevant.x.rb5) {
  print(ggplot(sub_set_rb5, aes(y=eval(parse(text=feature)), x=Date)) +
  geom_smooth(method = "lm", aes(group = 1)) + geom_jitter(alpha = .5) + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) + ggtitle(feature))
}

#COUNRTY
for (feature in relevant.x.country5) {
  print(ggplot(sub_set_country5, aes(y=eval(parse(text=feature)), x=Date)) +
  geom_smooth(method = "lm", aes(group = 1)) + geom_jitter(alpha = .5) + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) + ggtitle(feature))
}
```

------------------------------------------------------------------------

------------------------------------------------------------------------
